PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/elephone/p9000/vendor/bin,system/vendor/bin)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/elephone/p9000/vendor/etc,system/vendor/etc)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/elephone/p9000/vendor/lib,system/vendor/lib)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/elephone/p9000/vendor/lib64,system/vendor/lib64)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/elephone/p9000/vendor/xbin,system/vendor/xbin)
